### ISSUE TITLE
Mean Angle Error （MAE）Comparions

### ISSUE THREAD

**Issue by Xuehao-Gao** [Droliven/MSRGCN#4]
Can you provide the official MAE performance of MSRGCN to help others compare it with other methods more comprehensively? 

Many Thanks

**Comment by Droliven** [comment]
As what is argured by Wei Mao et al., angle representation is ambiguous, you could find it in the Fig 4 of their paper, that is the reason why we use 3D coordinate representation, instead of the angle representation .

@inproceedings{mao2019learning,
  title={Learning trajectory dependencies for human motion prediction},
  author={Mao, Wei and Liu, Miaomiao and Salzmann, Mathieu and Li, Hongdong},
  booktitle={Proceedings of the IEEE/CVF International Conference on Computer Vision},
  pages={9489--9497},
  year={2019}
}
